[package]
name = "axum-askama-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
askama = "0.15"
askama_web = { version = "0.15", features = ["axum-0.8"] }
axum = "0.8"
htmx-form-errors = { path = "../.." }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
validator = { version = "0.20", features = ["derive"] }
